### ISSUE TITLE
Music won't stop playing

### ISSUE THREAD

**Issue by Korgen1** [Tajam/jext-spigot-plugin#2]
Music keeps playing even after being removed from jukebox. Another song can then be put in the jukebox and they will overlap, only way to stop them is to relog.

**Comment by Korgen1** [comment]
This is on Paper 1.16.3 to be clear.

**Comment by Tajam** [comment]
It would be great if you could write down the reproduce procedure. Does the console shows any error?

**Comment by Korgen1** [comment]
I just put in the music disc, it removes it from my inventory and the music plays. When I click the jukebox, the disc pops out but the music keeps playing. I am able to manually disable it with the /stopsound command. Nothing in the console.

**Comment by Korgen1** [comment]
Also, something I noticed. No matter how far away I go from the jukebox it still plays full volume.

**Comment by Korgen1** [comment]
Oh, damn. It was a compatibility problem with a plugin called "MusicBox" that plays NBS files. Sorry for possibly wasting your time.

**Comment by GordonsBeard** [comment]
> Also, something I noticed. No matter how far away I go from the jukebox it still plays full volume.

This sounds like it could be related to the .ogg file not being in mono.
