### ISSUE TITLE
1.17 Update Soon?

### ISSUE THREAD

**Issue by Garfieldwxg55** [Tajam/jext-spigot-plugin#7]
Hi, I have been using this plugin on my server for awhile now, and recently I updated it to Spigot 1.17. Upon doing this, however, I noticed that the plugin stops working. Any custom music disc placed in a jukebox will just play as a normal disc 11. A 1.17 update would be greatly appreciated.

**Comment by etmclovin** [comment]
its not jext that is the problem its ProtocolLib which has recently gotten a 1.17 update

https://github.com/dmulloy2/ProtocolLib/issues/1209

**Comment by Garfieldwxg55** [comment]
Forgot to close this
